spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: "jdbc:h2:c:/test/local"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
